### ISSUE TITLE
Using TSL-UMD as an Action - UMD Message doesn't accept variables

### ISSUE THREAD

**Issue by allen-harris** [bitfocus/companion-module-tslproducts-umd#10]
Hi,

I am using Companion 3.0.0.  I am trying to use a Trigger to update my Decimator MD-QUAD multiviewer UMDs with the current input assigned to the relevant output of my Videohub.

The trigger works, I get a tally, and the UMD message is updated, but if I use a Companion variable as the UMD message, the variable name is displayed rather than the value.  

Am I missing something?

It took me a bit to figure out that I needed to use UDP as it isn't noted in the documentation other than V5 supporting both UDP and TCP.

Great tools.  Thanks for taking the time to create these modules.

**Comment by josephdadams** [comment]
Every module has to be coded/programmed to parse the value of a variable if the variable is placed into a text field. So this module does not have that feature at this time.

**Comment by Seanbucks** [comment]
I would also love to be able to do the same thing

**Comment by josephdadams** [comment]
this is done in the latest v2.0.0 of this module

**Comment by allen-harris** [comment]
Thanks so much for implementing this.  It works like a charm, updating both
my Decimator UMDs and the source names into my ATEM switcher.
