### ISSUE TITLE
TSL Module

### ISSUE THREAD

**Issue by Keksstar** [bitfocus/companion-module-tslproducts-umd#2]
**Describe the feature**
The TSL protocol is used in many UMD (under monitor displays, e.g. TSL, BTS), multiviewers (e.g. Decimator, Kaleido, etc.) and Monitors (e.g. TVlogic, Marshall, Ikan, etc.)

**Is this platform dependent (windows, mac, ..)?**
Independant. Just needs an Com-Port for serial connection. (how can this be done? I´m no programmer... I have no idea)

**If documentation is required to implement, do you know where to find it?**
https://tslproducts.com/media/1959/tsl-umd-protocol.pdf

**Usecases**
Would be great to have the ability to change UMDs corresponding to the switching of an Video Matrix. (like BMD Videohub, etc)

**Comment by haakonnessjoen** [comment]
This is a bit weird, since the spec clearly says that the data should only be displayable data. And 0x20 is a space. So if anything, the loop ends a bit early with the last byte being 00 and not 0x20.

> Display Data = 16 displayable ASCII characters
> (16 bytes) in the range 20 hex to 7E hex.
> All 16 characters must be sent.

Could you test sending 803043414d20312020202020202020202020 ? (the last byte fixed)

**Comment by haakonnessjoen** [comment]
Or test latest build, which should fix the last byte.

**Comment by Keksstar** [comment]
Yeah the specs are a little bit unclear on this... we already had a lot of testing for Universe with the same topic...

Sending 0x20 results in the behaviour that the display is wrong alligned. When it´s normally centered the text is then on the left due to the amount of spaces.
Just sending 0x00 is fine. You just need the correct length of the string.

**Comment by Keksstar** [comment]
Checked it, all works fine now!

But can we please also add an TCP transport version? All the data modems using are in TCP and getting conflicts with other software when I have to move them to UDP. I hope it´s just copy&paste and change somewhere UDP to TCP?

**Comment by Keksstar** [comment]
Well..... found an Bug...
TSL Address 0-9 works fine, 10 and above doesn´t work

**Comment by roddypratt** [comment]
@Keksstar  The address decode should be fixed in commit 7c5e15bd2a9dc1f10a2ba79f25365147e1227e64

What's the device using TSL UMD over TCP?  From a sender's point of view, the main change is that TCP is connection-oriented. (With receiver code, you need to act as a server and handle stream-based input  - checking for start bytes, partial packets, etc...)

**Comment by JeffreyDavidsz** [comment]
Fixed by @roddypratt

**Comment by momosh13** [comment]
> Looked into it. Sadly TSL 3.1 isn´t working.
> 
> Example for: TSL address: 0, Text: "CAM 1", with Tally off What you are sending: 803043414d20312020202020202020202000 What it needs to be: 803043414d20310000000000000000000000 I generated the second one in "Universe" - it´s working. Checked it with an Decimator DMON-16S.

Hi, I'm trying to test your hex strings and no luck, I bought this converter from amazon, using this software http://www.viewprotech.com/wap/index.php?ac=article&at=read&did=350
 to send your commands, and the dmon-16 not responding any of your commands, please tell me, what you think, I'm possible doing wrong here? Thank you 
![IMG_2622](https://github.com/bitfocus/companion-module-tslproducts-umd/assets/5689051/66dcf479-34c2-49b0-8916-6cf97028c75e)

>

**Comment by josephdadams** [comment]
@momosh13 are you sure you’ve wired this correctly and have your baud rates correct?
