### ISSUE TITLE
V4 protocol throws an error

### ISSUE THREAD

**Issue by roddypratt** [bitfocus/companion-module-tslproducts-umd#3]
![image](https://user-images.githubusercontent.com/1199520/69263124-97fe3d00-0bbc-11ea-8179-b6f673c0c8de.png)

![image](https://user-images.githubusercontent.com/1199520/69263269-e14e8c80-0bbc-11ea-9fd8-0535dfbc0060.png)

Also, I'm not sure the checksum calculation is correct.  I'm new to Companion dev but will try and sort out a pull request for these...

**Comment by JeffreyDavidsz** [comment]
you did ;-)
