### ISSUE TITLE
UMD V5.0 not changing tally address

### ISSUE THREAD

**Issue by Boguinhos** [bitfocus/companion-module-tslproducts-umd#7]
I have a doubt, and sorry if i am not correct, but accordingly to my tests it seems that changing tally address on v5.0 TCP and UDP does not reflect on tally output address change.

https://github.com/bitfocus/companion-module-tslproducts-umd/blob/c8ed64650c578758b24e68f2c14db5f26d1b6b89/index.js#L404

and 

https://github.com/bitfocus/companion-module-tslproducts-umd/blob/c8ed64650c578758b24e68f2c14db5f26d1b6b89/index.js#L431

this should be "opt.address" ,right?

or changing 

https://github.com/bitfocus/companion-module-tslproducts-umd/blob/c8ed64650c578758b24e68f2c14db5f26d1b6b89/index.js#L209
and
https://github.com/bitfocus/companion-module-tslproducts-umd/blob/c8ed64650c578758b24e68f2c14db5f26d1b6b89/index.js#L265

to "id: 'index' "

Am i thinking wrong or missing out on something?
thanks.

**Comment by josephdadams** [comment]
Submit a PR for this?

**Comment by josephdadams** [comment]
fixed in latest
