### ISSUE TITLE
UMD Text dynamic ?

### ISSUE THREAD

**Issue by Dandefer95** [bitfocus/companion-module-tslproducts-umd#9]
Hello,

I'm looking for the way to send a variable in the UMD message field, as you can see below.

![Capture](https://user-images.githubusercontent.com/63956700/187037724-38911cac-5975-4543-a5cf-c2ad7d4a0ecc.PNG)

Actuallly, the variable is not interpreted, is there a tips to send the variable value instead ?

Regards,
Quentin.

**Comment by josephdadams** [comment]
This has to be implemented on a per module basis.

**Comment by josephdadams** [comment]
@Dandefer95 I just coded this for you and pushed it to the betas. I hope this helps you on your journey. Have a nice day

**Comment by Dandefer95** [comment]
Hello !

Woa, thank you for you fast answer and coding !
I'm a beginner with companion, how I can use the version 1.2.5 ? On the "Connection library" it's the 1.2.3 version who is online.

Regards,
Quentin.

**Comment by josephdadams** [comment]
Upgrade to a recent beta build

**Comment by Dandefer95** [comment]
Ok I got it.
So the variable reading working well but I have an issue on the variable value refresh.
I mean, if I set up a custom variable with a value to 5, at the initialization trigger text umd will be correct but if I modify my custom value to 6, the UMD will continue to send 5.

**Comment by josephdadams** [comment]
Yes the action only runs when you press the button.  Maybe you could set up a trigger to send that action whenever the variable changes value.

**Comment by Dandefer95** [comment]
When I put a variable in umd message, it transform to his value after the first action
![image](https://user-images.githubusercontent.com/63956700/187082103-8e688755-1c41-498d-87a3-b54a84711d3a.png)
![image](https://user-images.githubusercontent.com/63956700/187082122-c5654a39-ed8c-4d62-b1dc-79944f7627c7.png)

**Comment by Dandefer95** [comment]
Whether it is a trigger or a button and even if I set up a trigger to send that action whenever the variable changes value. It's the same value sended.
At the moment who the button or the trigger is define, it doesn't refresh the value. I tried a desable/enable a triger too.
However, the "test action" button, works well, it check the value but it's a mannually action.
